#!/bin/bash -login
 
#PBS -l walltime=2:00:00,nodes=1:ppn=1,mem=2gb
#PBS -j oe
#PBS -t 18411-18510

### change to the working directory where your code is located
cd ${SCRATCH}/driftextinction/config_files
 
### call your executable
./avida -set DATA_DIR ../data_fixedmut/replicate_${PBS_ARRAYID} -set RANDOM_SEED ${PBS_ARRAYID} -set WORLD_X 10 -set WORLD_Y 1 -set BIRTH_METHOD 4 -set VERBOSITY 0 -set COPY_MUT_PROB 0.0 -set DIVIDE_MUT_PROB 0.15 -set DIVIDE_INS_PROB 0.005 -set DIVIDE_DEL_PROB 0.005 -set STERILIZE_UNSTABLE 1