#!/bin/bash -login
 
#PBS -l walltime=1:00:00,nodes=1:ppn=1,mem=2gb
#PBS -j oe

### change to the working directory where your code is located
cd ${HOME}/Documents/driftextinction/config_files
 
### call your executable
./avida -a -set DATA_DIR .. -set ANALYZE_FILE analyze_lethalmeasure_finaldominant.cfg -set EVENT_FILE events_lethalmeasure.cfg -set WORLD_X 10 -set WORLD_Y 1 -set BIRTH_METHOD 4 -set VERBOSITY 0 -set COPY_MUT_PROB 0.01 -set DIVIDE_INS_PROB 0.005 -set DIVIDE_DEL_PROB 0.005 -set STERILIZE_UNSTABLE 1