#!/bin/bash -login
 
#PBS -l walltime=1:00:00,nodes=1:ppn=1,mem=2gb
#PBS -o /mnt/ls15/scratch/users/labartho/driftextinction/sub_files/output
#PBS -j oe
#PBS -t 11025-11124

### change to the working directory where your code is located
cd ${SCRATCH}/driftextinction/config_files
mkdir -p ../data_lethalmeasure_varmut/genotype9_01
 
### call your executable
./avida -set DATA_DIR ../data_lethalmeasure_varmut/genotype9_01/replicate_${PBS_ARRAYID} -set EVENT_FILE event_files_lethalmeasure_replay/events_lethalmeasure_replay_genotype9.cfg -set RANDOM_SEED ${PBS_ARRAYID} -set WORLD_X 10 -set WORLD_Y 1 -set BIRTH_METHOD 4 -set VERBOSITY 0 -set COPY_MUT_PROB 0.01 -set DIVIDE_INS_PROB 0.0 -set DIVIDE_DEL_PROB 0.0 -set STERILIZE_UNSTABLE 1 -set OFFSPRING_SIZE_RANGE 1.0